spring.application.name=finance-tracker-api

server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

telegram.bot.username=${TELEGRAM_BOT_USERNAME:${YOUR_BOT_USERNAME:bot_username}}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:${YOUR_BOT_TOKEN:bot_token}}
telegram.chat.id=${TELEGRAM_CHAT_ID:656552585}